version: "3.8"
services:
  fairydb-server:
    build: .
    image: zelshahawy/fairydb:latest
    # force /usr/local/bin/server as the entrypoint, no extra args
    entrypoint: ["server"]
    ports:
      - "3333:3333"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/health"]
      interval: 2s
      retries: 5


  fairydb-cli:
    image: zelshahawy/fairydb:latest
    depends_on:
      - fairydb-server

    # override entrypoint so we run the CLI binary
    entrypoint: ["cli-crusty"]
    # keep stdin & tty if you need interactivity
    stdin_open: true
    tty: true

