name: Cargo Clippy and Format Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Cargo Registry and Target
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install Rust Stable Toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
      
    - name: Check Formatting
      run: >
        cargo check --all --all-targets --verbose --no-default-features && 
        cargo fmt --all -- --check && 
        cargo clippy --all --all-targets --verbose --no-default-features &&
        cargo clippy --all --all-targets --verbose --all-features &&
        echo "All Ok!"